### ISSUE TITLE
Why are post metas are stored as an array instead of sperarate keys

### ISSUE THREAD

**Issue by joehoyle** [adamsilverstein/wp-post-meta-revisions#13]
I noticed for some reason, all meta for a single key is stored as a single meta key (serialized array) in the revision meta, this makes calling `get_post_meta` on a revision return an array-encapsulated data rather than the data you would get from calling `get_post_meta` on the parent post. I just wondered why that was?

**Comment by adamsilverstein** [comment]
Hmm, I need to look at this more closely, I am seeing this as well.

**Comment by adamsilverstein** [comment]
@joehoyle I pushed a proposed fix for this issue in https://github.com/adamsilverstein/wp-post-meta-revisions/pull/27 - if you have a chance can you give it a test? Thanks

**Comment by roborourke** [comment]
Hey @adamsilverstein, I'm not sure #27 is the solution as meta data can be stored in any of the following ways:

 1. Single string value
 2. Serialised array / object value
 3. Multiple entries of either of the above with the same key

Using `get_post_meta()` with `$single` set to true you'll lose data in scenario 3.

I think at some point some assumptions would have to be made about the data if it's an array so if the response from `get_post_meta( $id, $key )` is:

1. A numbered array with one entry
   1. Store the array value eg `add_metadata( 'post', $id, $key, $meta[0] )`
   2. When retrieved using `get_post_meta( $id, $key )` should be an array with one entry
2. A numbered array with multiple entries
  1. Loop over the array and call `add_metadata( 'post', $id, $key, $item )`
  2. When retrieving the metadata you should get an array of the items back

It should be enough to change it in the following way:

```php
$meta_values = get_post_meta( $post_id, $meta_key );

/*
 * Use the underlying add_metadata() function vs add_post_meta()
 * to ensure metadata is added to the revision post and not its parent.
 */
foreach ( $meta_values as $meta_value ) {
    add_metadata( 'post', $revision_id, $meta_key, $meta_value );
}
```

There are then going to need to be updates to the way revision is restored and also compared I think.

**Comment by danielbachhuber** [comment]
Hi @joehoyle

**Comment by adamsilverstein** [comment]
Note: Planning to implement https://github.com/adamsilverstein/wp-post-meta-revisions/pull/56 as soon as we can get to expanding tests for it.
