### ISSUE TITLE
Did this ever work?

### ISSUE THREAD

**Issue by joelstransky** [adamsilverstein/wp-post-meta-revisions#18]
At this point I'm sure this plugin ever worked.
I already had Advanced Custom Fields installed when I installed this and so I thought was I was seeing was a working plugin. I've since wiped and re-installed WP with this being the only active plugin and I cannot see it work in the least. No matter what I change, I cannot see custom fields in the revision timeline nor to their values come back when I restore old versions.
Can you please help?

**Comment by joelstransky** [comment]
I'm still confused.
I just did a fresh install of WP 4.5.1, added a custom field to the default post (see image) and added the following to the theme's functions.php
```
function add_meta_keys_to_revision( $keys ) {
    $keys[] = 'my_test_field';
    return $keys;
}
add_filter( 'wp_post_revision_meta_keys', 'add_meta_keys_to_revision' );
```
![image](https://cloud.githubusercontent.com/assets/200472/14930037/b54144a0-0dfc-11e6-9953-e64a02bcc1c7.png)

I then changed the value of the custom field and updated the post. No version was created but the change was kept. In fact, no versions got created until I made a change to a default field (title, content, excerpt) and even then, those revisions did not contain custom field changes and changes to custom fields had no effect.

What am I doing wrong?

**Comment by kirkov** [comment]
Had the same issue. After some debugging I found out it does not work with the built in "Custom Fields" metabox. Because the name is "nested": 

    <input name="meta[217][key]" id="meta-217-key" type="text" size="20" value="xxx">

The plugin only handles top level names, like: 

    <input name="my_field_name" ... >

**Comment by adamsilverstein** [comment]
@kirkov have you tried passing the complete id of each revisioned field to the wp_post_revision_meta_keys filter? This should work correctly, if not I can try to figure out why.

**Comment by kirkov** [comment]
@adamsilverstein I can't remember as I'm not working with wordpress anymore.

**Comment by joelstransky** [comment]
Advanced Custom Fields has a rather decent custom fields revisioning solution. Might be a good reference.
