### ISSUE TITLE
WordPress hosted plugin zip contains trunk folder

### ISSUE THREAD

**Issue by DeanMarkTaylor** [adamsilverstein/wp-post-meta-revisions#4]
The file hosted here:
https://wordpress.org/plugins/wp-post-meta-revisions/
https://downloads.wordpress.org/plugin/wp-post-meta-revisions.0.1.8.zip

contains files not required for the plugin to be used, including an additional trunk folder.

**Comment by adamsilverstein** [comment]
@DeanMarkTaylor - thanks for pointing this out, corrected!

https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=1232693%40wp-post-meta-revisions&old=1065694%40wp-post-meta-revisions&sfp_email=&sfph_mail=
