### ISSUE TITLE
Beta updates appear to be older than the current release

### ISSUE THREAD

**Issue by DeanMarkTaylor** [adamsilverstein/wp-post-meta-revisions#5]
Using the beta tester plugin to indicate and download updates
https://wordpress.org/plugins/plugin-beta-tester/

![image](https://cloud.githubusercontent.com/assets/52425/6088768/fc93f6b0-ae51-11e4-8f85-6f857a59b544.png)

Version 0.6 changes seem older than 0.1.8.

**Comment by adamsilverstein** [comment]
Thanks for the report @DeanMarkTaylor - this should be fixed now, let me know if you still have this issue.
