### ISSUE TITLE
Preview and autosave does not work

### ISSUE THREAD

**Issue by Nimdraug** [adamsilverstein/wp-post-meta-revisions#9]
Using this plugin to get meta data storing in revisions on a client's website. Whereas the meta data stores fine after registering their meta keys, I cannot seem to get the preview functionality working.
I noticed that it was turned off by default so I assume this is a known issue. But since the client asked to be able to preview their changes I thought I'd enable it and try and get it working.
Sadly I ran out of time for this but what I found was that the autosave revision does have meta data stored against it, but that the data is empty. It seems that the _wp_autosave_post_revisioned_meta_fields method does not get called when the autosave gets created.

Hope someone will find the above helpful in solving this as previewing the meta changes would be a fairly nice feature to have. If I get more time later I'll give it another go.

**Comment by adamsilverstein** [comment]
Hi @Nimdraug!

Thanks for your feedback. I do want to work on getting post meta to display in the UI, the tricky part is if its not just text stored in meta thats easy to 'diff'. I have a new approach though that may be better.

In the mean time, to address your goal of previewing your post with the revisioned meta data, please check out the patch here:

https://core.trac.wordpress.org/ticket/20299#comment:47

I think this does just what you need and would really appreciate your feedback on how it works and if it solves your issue. I will check the patch and make sure it applies cleanly, I haven't refreshed it in a while.

**Comment by adamsilverstein** [comment]
@Nimdraug I have worked more on displaying the meta on the revisions screen, to test please check out https://github.com/adamsilverstein/wp-post-meta-revisions/tree/features/display-meta-on-revisions-ui

Closing this for now. Please reopen or open a new issue if you still have questions.
